name: Release Build

on:
  push:
    tags:
      - "v*"

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  build_android:
    name: Build Android
    needs: [ci]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install Android SDK Platform 37
        run: yes | "$ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager" "platforms;android-37.0" "build-tools;37.0.0"

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Rename APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/haven-app-android.apk

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: haven-app-android
          path: build/app/outputs/flutter-apk/haven-app-android.apk

  build_windows:
    name: Build Windows
    needs: [ci]
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Create MSIX
        run: dart run msix:create

      - name: Upload MSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: haven-app-windows
          path: build/windows/x64/runner/Release/haven.msix

  create_release:
    name: Create Release
    needs: [build_android, build_windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            haven-app-android/haven-app-android.apk
            haven-app-windows/haven.msix
          generate_release_notes: true
